import {readFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import {defineConfig, type DefaultTheme} from 'vitepress';

/**
 * The API Reference sidebar is generated by TypeDoc (`pnpm docs:api`) into
 * `docs/api/typedoc-sidebar.json`. That file is gitignored, so it may be
 * absent during a fresh checkout — load it defensively to keep `vitepress`
 * config evaluation from throwing before the reference has been generated.
 */
function loadApiSidebar(): DefaultTheme.SidebarItem[] {
  try {
    const path = fileURLToPath(
      new URL('../api/typedoc-sidebar.json', import.meta.url)
    );
    return JSON.parse(readFileSync(path, 'utf-8')) as DefaultTheme.SidebarItem[];
  } catch {
    return [];
  }
}

export default defineConfig({
  lang: 'en-US',
  title: 'ADAMANT JS API',
  description:
    'TypeScript SDK for the ADAMANT blockchain: node access, accounts, transactions, encrypted messaging, and wallet helpers.',
  cleanUrls: true,
  lastUpdated: true,
  ignoreDeadLinks: false,

  head: [
    ['link', {rel: 'icon', href: 'https://adamant.im/favicon.ico'}],
  ],

  themeConfig: {
    nav: [
      {text: 'Guide', link: '/guide/getting-started'},
      {text: 'API Reference', link: '/api/'},
      {
        text: 'v3',
        items: [
          {
            text: 'Changelog',
            link: 'https://github.com/Adamant-im/adamant-api-jsclient/releases',
          },
          {
            text: 'npm',
            link: 'https://www.npmjs.com/package/adamant-api',
          },
        ],
      },
    ],

    sidebar: {
      '/guide/': [
        {
          text: 'Introduction',
          items: [
            {text: 'Getting Started', link: '/guide/getting-started'},
            {text: 'Library Initialization', link: '/guide/library-initialization'},
            {text: 'Modular Imports', link: '/guide/modular-imports'},
            {text: 'Reliability', link: '/guide/reliability'},
          ],
        },
        {
          text: 'ADM',
          items: [
            {text: 'ADM Key Pairs', link: '/guide/adm-key-pairs'},
            {text: 'Encrypting & Decrypting Messages', link: '/guide/encryption'},
            {text: 'Forming & Signing Transactions', link: '/guide/transactions'},
            {text: 'Querying Transactions', link: '/guide/querying-transactions'},
            {text: 'Calculating Transaction ID', link: '/guide/transaction-id'},
            {text: 'WebSocket Connections', link: '/guide/websocket'},
          ],
        },
        {
          text: 'Wallets',
          items: [
            {text: 'External Coin Wallets', link: '/guide/external-coins'},
            {text: 'Wallet Metadata', link: '/guide/wallet-metadata'},
          ],
        },
      ],
      '/api/': loadApiSidebar(),
    },

    socialLinks: [
      {
        icon: 'github',
        link: 'https://github.com/Adamant-im/adamant-api-jsclient',
      },
    ],

    editLink: {
      pattern:
        'https://github.com/Adamant-im/adamant-api-jsclient/edit/master/docs/:path',
      text: 'Edit this page on GitHub',
    },

    search: {
      provider: 'local',
    },

    footer: {
      message: 'Released under the GPL-3.0 License.',
      copyright: 'ADAMANT developer community',
    },
  },
});
